import { Octokit } from "@octokit/rest";
import { getConfig } from "../config";
import { createChildLogger } from "../utils/logger";

const log = createChildLogger({ module: "self-improve-github" });

let _octokit: Octokit | null = null;

function getOctokit(): Octokit | null {
	const config = getConfig();
	if (!config.GITHUB_TOKEN || !config.GITHUB_REPO_OWNER) {
		log.debug("GitHub not configured");
		return null;
	}
	if (!_octokit) {
		_octokit = new Octokit({ auth: config.GITHUB_TOKEN });
	}
	return _octokit;
}

export interface PRRequest {
	title: string;
	description: string;
	branch: string;
	changes: Array<{ path: string; content: string }>;
}

export interface IssueRequest {
	title: string;
	body: string;
	labels?: string[];
}

export async function createPR(request: PRRequest): Promise<string | null> {
	const octokit = getOctokit();
	if (!octokit) return null;

	const config = getConfig();
	const owner = config.GITHUB_REPO_OWNER!;
	const repo = config.GITHUB_REPO_NAME;

	try {
		const { data: repoData } = await octokit.repos.get({ owner, repo });
		const defaultBranch = repoData.default_branch;

		const { data: ref } = await octokit.git.getRef({
			owner,
			repo,
			ref: `heads/${defaultBranch}`,
		});
		const baseSha = ref.object.sha;

		const { data: baseCommit } = await octokit.git.getCommit({
			owner,
			repo,
			commit_sha: baseSha,
		});

		const tree = [];
		for (const change of request.changes) {
			const { data: blob } = await octokit.git.createBlob({
				owner,
				repo,
				content: Buffer.from(change.content).toString("base64"),
				encoding: "base64",
			});
			tree.push({
				path: change.path,
				mode: "100644" as const,
				type: "blob" as const,
				sha: blob.sha,
			});
		}

		const { data: newTree } = await octokit.git.createTree({
			owner,
			repo,
			base_tree: baseCommit.tree.sha,
			tree,
		});

		const { data: newCommit } = await octokit.git.createCommit({
			owner,
			repo,
			message: `[self-improve] ${request.title}`,
			tree: newTree.sha,
			parents: [baseSha],
		});

		await octokit.git.createRef({
			owner,
			repo,
			ref: `refs/heads/${request.branch}`,
			sha: newCommit.sha,
		});

		const { data: pr } = await octokit.pulls.create({
			owner,
			repo,
			title: `[Self-Improve] ${request.title}`,
			body: `## Auto-generated Improvement Proposal\n\n${request.description}\n\n---\n*This PR was automatically generated by the trading agent's self-improvement system. Please review carefully before merging.*`,
			head: request.branch,
			base: defaultBranch,
		});

		log.info({ prNumber: pr.number, prUrl: pr.html_url }, "PR created");
		return pr.html_url;
	} catch (error) {
		log.error({ error }, "Failed to create PR");
		return null;
	}
}

export async function createIssue(request: IssueRequest): Promise<string | null> {
	const octokit = getOctokit();
	if (!octokit) return null;

	const config = getConfig();
	const owner = config.GITHUB_REPO_OWNER!;
	const repo = config.GITHUB_REPO_NAME;

	try {
		const { data: issue } = await octokit.issues.create({
			owner,
			repo,
			title: `[Agent Suggestion] ${request.title}`,
			body: `## Agent-Identified Change Request\n\n${request.body}\n\n---\n*This issue was automatically created by the trading agent's self-improvement system.*`,
			labels: request.labels ?? ["agent-suggestion"],
		});

		log.info({ issueNumber: issue.number, issueUrl: issue.html_url }, "Issue created");
		return issue.html_url;
	} catch (error) {
		log.error({ error }, "Failed to create issue");
		return null;
	}
}
